server:
  port: 8080

spring:
  application:
    name: starter
  datasource:
    url: jdbc:mysql://localhost:3306/starter?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123 #selaludihapus
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 5000
      max-lifetime: 30000
      connection-timeout: 5000
      validation-timeout: 3000
      keepalive-time: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /springboot-starter-template/v3/api-docs

application:
  name: starter
  version: @project.version@
